apiVersion: v1
kind: Namespace
metadata:
  name: tgs-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgs-pod #Base pod name
  namespace: tgs-system
spec:
  selector:
    matchLabels:
      app: tgs
  template:
    metadata:
      labels:
        app: tgs
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: tgs-api
          image: tgs_api_image
          ports:
            - name: tgs-api
              containerPort: 3000
            - name: tgs-api-debug
              containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: tgs-service
  namespace: tgs-system
spec:
  type: ClusterIP
  selector:
    app: tgs
  ports:
    - name: tgs-api
      port: 3000
      targetPort: tgs-api
    - name: tgs-api-debug
      port: 4000
      targetPort: tgs-api-debug
