apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/api-pod/
patchesStrategicMerge:
- kind-tgs-patch.yaml
images:
- name: tgs_api_amd64
  newTag: "1.0"
- name: tgs_api_image
  newName: tgs_api_amd64
  newTag: "1.0"
