### Create aggregator
POST {{BASE_URL_V1}}/aggregator
x-api-key: {{API_KEY}}
aggregator: {{AGGREGATOR_ID}}

{
    "name": "{{DEFAULT_AGGREGATOR_CODE}}",
    "code": "{{DEFAULT_AGGREGATOR_CODE}}",
    "apiKey": "{{API_KEY}}",
    "providerTimeout": 5000,
    "active": true,
    "type": "default",
    "paymentByTgs": true,
    "logoUrl": "https://image.shutterstock.com/image-vector/stripes-dots-circle-logo-vector-260nw-1139400776.jpg"
}

### Query Aggregator
GET {{BASE_URL_V1}}/aggregator?page=1&rows=100
x-api-key: {{API_KEY}}
aggregator: {{AGGREGATOR_ID}}

### Query By Id Aggregator
GET {{BASE_URL_V1}}/aggregator/{{AGGREGATOR_ID}}
x-api-key: {{API_KEY}}
aggregator: {{AGGREGATOR_ID}}

### Update Aggregator
PUT {{BASE_URL_V1}}/aggregator/{{AGGREGATOR_ID}}
x-api-key: {{API_KEY}}
aggregator: {{AGGREGATOR_ID}}

{
    "providerTimeout": 3000
}

### DELETE Aggregator
DELETE {{BASE_URL_V1}}/aggregator/{{AGGREGATOR_ID}}
x-api-key: {{API_KEY}}
aggregator: {{AGGREGATOR_ID}}