### Create Pack
POST {{BASE_URL_V1}}/pack
x-api-key: {{API_KEY}}
aggregator: {{AGGREGATOR_ID}}

{
    "name": "siege",
    "description": "all collaborator that are admin",
    "paymentMethod": "NDF",
    "enterpriseId": "{{ENTERPRISE_ID}}",
    "policyId": "{{POLICY_ID}}",
    "invoicingEntityId": "{{INVOICING_ID}}"
}

### Query Pack
GET {{BASE_URL_V1}}/pack?page=1&rows=100
x-api-key: {{API_KEY}}
aggregator: {{AGGREGATOR_ID}}

### Query By Id Pack
GET {{BASE_URL_V1}}/pack/{{PACK_ID}}
x-api-key: {{API_KEY}}
aggregator: {{AGGREGATOR_ID}}

### Update Pack
PUT {{BASE_URL_V1}}/pack/{{PACK_ID}}
x-api-key: {{API_KEY}}
aggregator: {{AGGREGATOR_ID}}

{
    "town": "sweden",
    "country": "estonia"
}


### Delete Pack
DELETE {{BASE_URL_V1}}/pack/{{PACK_ID}}
x-api-key: {{API_KEY}}
aggregator: {{AGGREGATOR_ID}}