### Create Team
POST {{BASE_URL_V1}}/policy
x-api-key: {{API_KEY}}
aggregator: {{AGGREGATOR_ID}}

{
    "name": "siege",
    "description": "all collaborator that are admin",
    "collaboratorBudget": 1000,
    "enterpriseId": "{{ENTERPRISE_ID}}",
    "startServiceTime": "07:00:00",
    "endServiceTime": "23:00:00",
    "budgetType": "monthly"
}

### Query Team
GET {{BASE_URL_V1}}/policy?page=1&rows=100
x-api-key: {{API_KEY}}
aggregator: {{AGGREGATOR_ID}}

### Query By Id Team
GET {{BASE_URL_V1}}/policy/{{POLICY_ID}}
x-api-key: {{API_KEY}}
aggregator: {{AGGREGATOR_ID}}

### Query By Enterprise
GET {{BASE_URL_V1}}/policy/enterprise/{{ENTERPRISE_ID}}
x-api-key: {{API_KEY}}
aggregator: {{AGGREGATOR_ID}}


### Update Team
PUT {{BASE_URL_V1}}/policy/{{POLICY_ID}}
x-api-key: {{API_KEY}}
aggregator: {{AGGREGATOR_ID}}

{
     "collaboratorBudget": 2000
}


### DELETE Team
DELETE {{BASE_URL_V1}}/policy/{{POLICY_ID}}
x-api-key: {{API_KEY}}
aggregator: {{AGGREGATOR_ID}}