name: Go Tests

on:
  pull_request:
    branches:
      - dev
      - staging
      - main

jobs:
  go_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: go test ./... 